<a href="https://colab.research.google.com/github/Arunimad/CCIR_ChatGPT_AI-Linguistics/blob/main/TA5_2(PyTorch_intro).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction and quickstart to Pytorch


PyTorch is an optimized Deep Learning tensor library based on Python and Torch and is mainly used for applications using GPUs and CPUs.

PyTorch consists of 4 main packages:

torch: a general purpose array library similar to Numpy that can do computations on GPU
torch.autograd: a package for automatically obtaining gradients
torch.nn: a neural net library with common layers and cost functions
torch.optim: an optimization package with common optimization algorithms like SGD, Adam, etc

Funfact

"PyTorch was initially an internship project for Adam Paszke, who at the time was a student of Soumith Chintala, one of the developers of Torch. Paszke and several others worked with developers from different universities and companies to test PyTorch. Chintala currently works as a researcher at Meta -- formerly Facebook -- which uses PyTorch as its underlying platform for driving all AI workloads."

In [ ]:
# import pytorch libraries
%matplotlib inline
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

Tensors - scalar, vector,matrix,and tensor

You will sometimes see a 1-dimensional tensor called a vector.

Likewise, a 2-dimensional tensor is often referred to as a matrix.

Anything with more than two dimensions is generally just called a tensor.

In [ ]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


Fun fact ..
.empty (); memory allocation

In [ ]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[ 8.0943e+30,  4.4099e-41, -1.9023e-36,  4.4097e-41],
        [ 8.0944e+30,  4.4099e-41,  7.7159e+30,  4.4099e-41],
        [ 8.0943e+30,  4.4099e-41, -1.9035e-36,  4.4097e-41]])


In [ ]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64)
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[0.8658, 0.7299, 0.3020],
        [0.9021, 0.3627, 0.9826]], dtype=torch.float64)
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [ ]:
print(f"This is the shape of our tensor: {c.shape}")

This is the shape of our tensor: torch.Size([2, 3])


In [ ]:
print(f"This is the data type of our tensor: {c.dtype}")

This is the data type of our tensor: torch.int32


tensor from python list

In [ ]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor from numpy

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
tens = torch.from_numpy(arr)
tens

tensor([[1, 2, 3],
        [4, 5, 6]])

Accessing our tensor

In [ ]:
test = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
test

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#To access a single value in the tensor (Keep in mind that Python indexing starts at 0):
print(f"Value in cell 1, 0: {test[1,0]}")
print(f"Value in cell 2, 2: {test[2,2]}")

Value in cell 1, 0: 4
Value in cell 2, 2: 9


In [ ]:
#To access a row in the tensor:
print(f"Row 0: {test[0]}")
print(f"Row 2: {test[2]}")

Row 0: tensor([1, 2, 3])
Row 2: tensor([7, 8, 9])


In [ ]:
#To access a column in the tensor:
print(f"Column 0: {test[:, 0]}")
print(f"Column 1: {test[:, 1]}")

Column 0: tensor([1, 4, 7])
Column 1: tensor([2, 5, 8])


Basic math in tensor

In [ ]:
test1 = test.clone()
test2 = test.clone()

In [ ]:
test1 + test2

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [ ]:
#Addition
torch.add(test1, test2)

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [ ]:
test1 - test2

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
#Subtraction
torch.sub(test1, test2)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
test1 * test2

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [ ]:
#Multiplication
torch.mul(test1, test2)

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [ ]:
test1 / test2

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#Division
torch.div(test1, test2)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#Matrix Multiplication
torch.matmul(test1, test2)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [ ]:
#Matrix concatenation
torch.cat([test1, test2], dim=1)

tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6],
        [7, 8, 9, 7, 8, 9]])

In [ ]:
#Transpose
test1.T
test2.T

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [ ]:
#also transpose
test1.t()
test2.t()

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

Sigmoid and tenh functions are common activation fucntions used in NNs

In [ ]:
#Sigmoid
torch.sigmoid(test)

tensor([[0.7311, 0.8808, 0.9526],
        [0.9820, 0.9933, 0.9975],
        [0.9991, 0.9997, 0.9999]])

In [ ]:
#Tanh
torch.tanh(test)

tensor([[0.7616, 0.9640, 0.9951],
        [0.9993, 0.9999, 1.0000],
        [1.0000, 1.0000, 1.0000]])